pimcore:
    objects:
        class_definitions:
            data:
                map:
                    advancedManyToManyObjectRelation: App\Model\DataObject\ClassDefinition\Data\AdvancedManyToManySkillOrGroupRelation
